blueprints/ClothChange.py
from flask import Blueprint, render_template, redirect, url_for
from flask import request
import config
from exts import db, csrf
import os
from models import Cloth

bp = Blueprint("ClothChange", __name__, url_prefix="/cloth/")


@bp.route('/')
def my_wardrobes():
    clothes = Cloth.query.all()
    # return "success"
    return render_template('wardrobes.html', clothes=clothes)


@bp.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST' and 'file' in request.files:
        f = request.files.get('file')  # 获取图片文件对象
        if not f:
            return 'Invalid image.', 400
        filename = f.filename  # 获取文件名
        f.save(os.path.join(config.CLOTH_UPLOAD_PATH, filename))
        # 保存图片文件
        last_cloth = Cloth.query.order_by(-Cloth.uid).first()
        cloth = Cloth(
            cloth_name=filename,
            uid=last_cloth.uid + 1,
            status=False
        )
        db.session.add(cloth)
        db.session.commit()
    return render_template('upload.html')


@bp.route('/myconsole')
def console():
    return redirect(url_for('ClothChange.my_wardrobes'))


@bp.route('/myconsole/<int:uid>/')
def detail_page(uid):
    cloth = Cloth.query.filter_by(uid=uid).first()
    return render_template('myconsole.html', cloth=cloth)


@csrf.exempt
@bp.route('/status/<cloth_name>', methods=['POST'])
def to_cloth(cloth_name):
    cloth = Cloth.query.filter_by(cloth_name=cloth_name).first()
    if not cloth.status:
        worn_cloth = Cloth.query.filter_by(status=True).first()
        if worn_cloth:
            worn_cloth.status = False
            db.session.add(worn_cloth)
    cloth.status = not cloth.status
    db.session.add(cloth)
    db.session.commit()
    return render_template('myconsole.html', cloth=cloth)

templates/base.html
<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/bootstrap.4.6.min.css') }}">
<!--    <link href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">-->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='images/site.webmanifest') }}">
    <title>SmartMirror|{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">智能镜子</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">SmartMirror<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/cloth/">我的衣柜</a>
                    </li>
<!--                    <li class="nav-item ml-2">-->
<!--                        <form class="form-inline my-2 my-lg-0" method="GET" action="#">-->
<!--                            <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="q">-->
<!--                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>-->
<!--                        </form>-->
<!--                    </li>-->
                </ul>
<!--                <ul class="navbar-nav">-->
<!--                    <li class="nav-item">-->
<!--                        <a class="nav-link" href="#">登录</a>-->
<!--                    </li>-->
<!--                    <li class="nav-item">-->
<!--                        <a class="nav-link" href="#">注册</a>-->
<!--                    </li>-->
<!--                </ul>-->
            </div>
        </div>
    </nav>

    <div class="container">
        {% block styles %}{% endblock %}
        {% block content %}{% endblock %}
        {% block scripts %}{% endblock %}
        {% block body %}{% endblock %}
    </div>
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

</html>

templates/index.html
{% extends "test.html" %}

{% block title %}Index{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2">
        </div>
        <!-- 第一部分：室内环境 -->
        <div class="col-md-4 col-md-push-2">
            <div class="card bg-light rounded">
                <div class="card-body">
                    <h5 class="card-title">室内环境</h5>
                    <p class="card-text">室温 : {{ indoor_env.temp_in }} ℃</p>
                    <p class="card-text">湿度 : {{ indoor_env.humi_in }} %</p>
                    <p class="card-text">环境质量 : {{ indoor_env.api_in }}</p>
                </div>
            </div>
        </div>

        <!-- 第二部分：当前天气 -->
        <div class="col-md-4 col-md-push-4">
            <div class="card bg-light rounded">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-5">
                            <h5 class="card-title">当前天气</h5>
                            <p class="card-text">天气 : {{ outdoor_climate.weather }}</p>
                            <p class="card-text">温度 : {{ outdoor_climate.temp_out }} ℃</p>
                            <p class="card-text">湿度 : {{ outdoor_climate.humi_out }} %</p>
                        </div>
                        <div class="col-md-7">
                            <img decoding="async" width="100" height="100"
                                 src="{{ url_for('static', filename='images/weather/'+weather_events[outdoor_climate.weather]+'.png') }}"
                                 class="img-responsive" alt=outdoor_climate.weather>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
    </div>

    <div class="row">
        <!-- 第三部分：天气预报 -->
        <div class="col-md-12 mt-3">
            <div class="card bg-light rounded">
                <div class="card-body">
                    <h5 class="card-title">天气预报</h5>
                    <div class="row">
                        {% for cast in forecasts %}
                            <div class="col-md-4">
                                <div class="card bg-light rounded">
                                    <div class="card-body">
                                        <div class="mb-3 mt-3">
                                            <div class="row">
                                                <div class="col-md-7">
                                                    <h6 class="text">{{ cast.date }}&emsp;周{{ week_num[cast.week] }}</h6>
                                                    <p class="text">白天天气 : {{ cast.day_weather }}</p>
                                                    <p class="text">白天温度 : {{ cast.day_temp }} ℃</p>
                                                    <p class="text">晚上天气 : {{ cast.night_weather }}</p>
                                                    <p class="text">晚上温度 : {{ cast.night_temp }} ℃</p>
                                                </div>
                                                <div class="col-md-5">
                                                    <img decoding="async" width="100" height="100"
                                                         src="{{ url_for('static', filename='images/weather/'+weather_events[cast.day_weather]+'.png') }}"
                                                         class="img-responsive" alt=cast.day_weather>
                                                    <img decoding="async" width="100" height="100"
                                                         src="{{ url_for('static', filename='images/weather/'+weather_events[cast.night_weather]+'.png') }}"
                                                         class="img-responsive" alt=cast.night_weather>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 切换到"wardrobes.html"的按钮 -->
    <div class="text-center mt-4">
        <a class="btn btn-primary" href="{{ url_for('ClothChange.my_wardrobes') }}" role="button">我的衣柜</a>
    </div>
{% endblock %}

templates/myconsole.html
{% extends "test.html" %}

{% block title %}Console{% endblock %}

{% block content %}
    <h2 class="mt-3">衣柜管理</h2>
    <hr>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-6 col-xs-3">
                <!-- 衣服图片 -->
                <div class="card text-center">
                    <div class="card-body">
                        <h5 class="card-title">{{ cloth.cloth_name }}</h5>
                        <a href="/cloth/myconsole/{{ cloth.uid }}">
                            <img decoding="async" src="{{ url_for('static', filename='images/uploads/' + cloth.cloth_name) }}" class="card-img-top img-responsive" alt=cloth.cloth_name>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <!-- 移除按钮 -->
                <form method="post" action="{{ url_for('api_v1.delete_cloth', cloth_name=cloth.cloth_name) }}">
                    <button type="submit" class="btn btn-danger" id="remove-btn">
                        <img width="100" height="100" src="{{ url_for('static', filename='images/delete.png') }}" alt="删除图标">
                    </button>
                </form>
                <br>
                <!-- 换衣按钮 -->
                <form method="post" action="{{ url_for('ClothChange.to_cloth', cloth_name=cloth.cloth_name) }}">
                    <button type="submit" class="btn btn-info" id="change-cloth-btn">
                        {% if cloth.status %}
                            <img width="100" height="100" src="{{ url_for('static', filename='images/takeoff.png') }}" alt="脱下图标">
                        {% else %}
                            <img width="100" height="100" src="{{ url_for('static', filename='images/change.png') }}" alt="换衣图标">
                        {% endif %}
                    </button>
                </form>
            </div>
            <div class="col-md-3">

            </div>
        </div>
    </div>

<!--    <script>-->
<!--        // 监听移除按钮的点击事件-->
<!--        document.getElementById('remove-btn').addEventListener('click', function() {-->
<!--            // 弹出确认框-->
<!--            var confirmRemove = confirm('确认从衣柜中移除这件衣服吗？');-->
<!--            if (confirmRemove) {-->
<!--                // 确认移除，发送请求到后端删除衣服信息-->
<!--                // 使用AJAX或其他适当的方式发送请求-->
<!--                var xhr = new XMLHttpRequest();-->
<!--                xhr.open('DELETE', '/api/v1/delete/clothes/' + cloth.cloth_name, true);-->
<!--                xhr.send();-->

<!--                window.location.href = '/cloth/';-->
<!--            }-->
<!--        });-->
<!--    </script>-->
{% endblock %}

templates/register.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="./static/bootstrap/bootstrap.4.6.min.css">
    <link rel="stylesheet" href="./static/css/init.css">
    <title>知了问答平台-注册</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">知了问答</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">发布问答</a>
                    </li>
                    <li class="nav-item ml-2">
                        <form class="form-inline my-2 my-lg-0" method="GET" action="#">
                            <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="q">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                        </form>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">注册</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row mt-4">
            <div class="col"></div>
            <div class="col">
                <form method="POST" action="#">
                    <div class="form-group">
                        <label for="exampleInputEmail1">邮箱</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                        <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用户</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">验证码</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="captcha">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">用户名</label>
                        <input type="text" class="form-control" name="username">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">密码</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">确认密码</label>
                        <input type="password" class="form-control" name="password_confirm">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">立即注册</button>
                </form>
            </div>
            <div class="col"></div>
        </div>
    </div>
</body>

</html>

templates/test.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>BootStrap模板测试</title>-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <link href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">-->
<!--    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>-->
<!--    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
<!--</head>-->
<!--<body>-->
<!--    <h1>模板测试</h1>-->
<!--&lt;!&ndash;    async: 异步解码图像，加快显示其他内容。&ndash;&gt;-->
<!--    <img decoding="async" src="./static/images/uploads/anshi.png" class="img-responsive" alt="响应式图像">-->

<!--</body>-->
<!--</html>-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SmartMirror|{% block title %}{% endblock %}</title>
    <!-- 引入Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.4.6.min.css') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/logo/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/logo/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/logo/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='images/site.webmanifest') }}">
    {% block styles %}{% endblock %}
    {% block head %}{% endblock %}
</head>
<body>
    <!-- 导航栏 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{{ url_for('static', filename='images/logo/apple-touch-icon.png') }}" width="30" height="30" alt="网站图标">
                SmartMirror
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/cloth/">我的衣柜</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/cloth/upload">上传</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/cloth/myconsole">管理</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- 主要内容 -->
    <div class="container mt-4">
        {% block content %}
        <!-- 子模板将填充此处的内容 -->
        {% endblock %}
    </div>
    {% block scripts %}{% endblock %}
    <!-- 引入Bootstrap的JavaScript文件 -->
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
</body>
</html>

templates/upload.html
{% extends 'test.html' %}

{% block title %}Upload{% endblock %}

{% block styles %}
    {{ super() }}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/dropzone.min.css') }}" type="text/css">
    {{ dropzone.style('margin: 20px 0; border: 2px dashed #0087F7; min-height: 400px;') }}
{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Upload</h1>
    </div>
    <div class="row">
        <div class="col-md-12">
            {{ dropzone.create(action='ClothChange.upload') }}
            <a class="btn btn-light float-right" href="{{ url_for('ClothChange.my_wardrobes') }}">Done</a>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
        <script src="{{ url_for('static', filename='js/dropzone.min.js') }}"></script>
    {{ dropzone.config() }}
{% endblock %}

{% block body %}
{% endblock %}

templates/wardrobes.html
{% extends "test.html" %}

{% block title %}MyWardrobes{% endblock %}

{% block content %}
    <h2 class="mt-3">我的衣柜</h2>
    <hr>

    <div class="container mt-4">
        <div class="row">
            {% for cloth in clothes %}
                <div class="col-md-6 col-sm-3 mb-4">
                    <div class="card text-center">
                        <div class="card-body">
                            <h5 class="card-title">{{ cloth.cloth_name }}</h5>
                            <a href="/cloth/myconsole/{{ cloth.uid }}">
                                <img decoding="async" src="{{ url_for('static', filename='images/uploads/' + cloth.cloth_name) }}" class="card-img-top img-responsive" alt=cloth.cloth_name>
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}

            <!-- 上传 -->
            <div class="col-md-2 col-sm-2 mb-4">
                <div class="card text-center">
                    <div class="card-body">
                        <a href="/cloth/upload">
                            <img decoding="async" width="100" src="{{ url_for('static', filename='images/upload.png') }}" class="card-img-top img-responsive" alt="上传">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 返回首页的按钮 -->
    <div class="text-center mt-4">
        <a class="btn btn-primary" href="/" role="button">首页</a>
    </div>
{% endblock %}